# Dependencies
markdown:             kramdown
highlighter:          rouge


# Gems
gems:
  - jekyll-sitemap


# Settings
exclude:              [CNAME, README.md, .gitignore]
sass:
  style:              compressed


# Site meta
title:                UWC Bloglist
tagline:              'A Jekyll theme'
keywords:             'skye, jekyll, template, github, project, single page, one page'
description:          'A collection of over 300 blogs in 20 languages written by UWC students from more than 55 countries at the 15 United World Colleges.'
url:                  http://uwcblogs.com
baseurl:              /

## replace analytics key below to enable tracking, leave blank to disable
google_analytics_key: 

author:
  name:               'Connor Bär'
  url:                'http://connorbaer.io'
  medium:             https://twitter.com/connor_baer
  github:             https://github.com/connor-baer
  twitter:            https://twitter.com/connor_baer
  facebook:           
  instagram:          https://instagram.com/connor_baer
  snapchat:           

version:              0.9.0-beta

github:
  repo:               https://github.com/connor-baer/uwcblogs