# Dependencies
markdown:             kramdown
highlighter:          rouge


# Gems
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-seo-tag


# Settings
color:                
  primary:            '#11DD88'
  primary-darker:     '#0EBE75'
  primary-lighter:    '#2EEF9F'
  primary-lighterer:  '#54F2B0'
exclude:              [CNAME, README.md, NOTES.md, .gitignore, js, sass, .gulpfile, node_modules]
sass:
  sass_dir:           _sass
  style:              compressed
permalink:            /:title/


# Site meta
title:                UWCxBlogs
tagline:              'A collection of UWC blogs.'
keywords:             'uwc, blog, blogs, bloglist, list, collection'
description:          'A collection of over 300 blogs in 20 languages written by UWC students from more than 55 countries at the 15 United World Colleges.'
url:                  http://uwcblogs.com
baseurl:              ''
logo:                 /assets/apple-icon-144x144.png
twitter:
  username:           connor_baer
facebook:
  app_id:             169140053203395

## replace analytics key below to enable tracking, leave blank to disable
google_analytics_key: UA-37412525-3
google_site_verification: Z-pc_HPc4XNBz8xg1fgtxO2MSIYLirZc2jWTNq0bJyM

author:
  name:               Connor Bär
  url:                http://connorbaer.io
  email:              hello@connorbaer.io
  twitter:            connor_baer

## Outputs the social links in the navigation. Re-arrange to change order.
nav_items:
  Medium:             https://medium.com/@connor_baer
  Twitter:            https://twitter.com/connor_baer
  Github:             https://github.com/connor-baer

version:              3.0.0

github:
  repo:               https://github.com/uwc/bloglist